services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    # image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    image: mysql:8.0
    container_name: db
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
    expose:
      - 3307
      - 33070
    ports:
      - '3307:3307'
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./server:/var/www/html
      - ./conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 80:80
    restart: always
    environment:
      - APACHE_DOCUMENT_ROOT
    entrypoint: ["/install-symfony.sh"]
  phpmyadmin:
    container_name: phpmyadmin
    image : arm64v8/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_HOSTS=db
    ports:
      - "3000:80"
    volumes:
      - ./phpmyadmin:/sessions
volumes:
  db_data:
